// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwkL8qlETOsC3B8WBdJWla9iTThaWKf4',
    appId: '1:928647770977:web:ded64cffe81a8888b7cb20',
    messagingSenderId: '928647770977',
    projectId: 'sos-app-c7667',
    authDomain: 'sos-app-c7667.firebaseapp.com',
    storageBucket: 'sos-app-c7667.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjObtVHP4c9O2yzQeC4_DtP26oExnic28',
    appId: '1:928647770977:android:c641b333cf87823fb7cb20',
    messagingSenderId: '928647770977',
    projectId: 'sos-app-c7667',
    storageBucket: 'sos-app-c7667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-Y08JV2P_1OHId5xZw_DeTBPCndi72M',
    appId: '1:928647770977:ios:86ef9e5bb7e3993db7cb20',
    messagingSenderId: '928647770977',
    projectId: 'sos-app-c7667',
    storageBucket: 'sos-app-c7667.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-Y08JV2P_1OHId5xZw_DeTBPCndi72M',
    appId: '1:928647770977:ios:bdf68dc825f84000b7cb20',
    messagingSenderId: '928647770977',
    projectId: 'sos-app-c7667',
    storageBucket: 'sos-app-c7667.appspot.com',
    iosBundleId: 'com.example.sample.RunnerTests',
  );
}
